spring.application.name=02_06_SpringRest_Emp
spring.datasource.url=jdbc:mysql://localhost:3306/springdemo
spring.datasource.username=root
spring.datasource.password=Ishwar@2003
spring.jpa.hibernate.ddl-auto=update
